language: java
sudo: false
before_script:
- pip install --user codecov
install: mvn install -DskipTests=true -Dgpg.skip=true -B -V
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
after_success:
- codecov
env:
  global:
    secure: N1exAfvij/J+G5zcV6drFsPvPKOIgvYRmrsyV0DrWt4l7IXVsVk4ZPRnqAD3V49KfVLZNVuBFzvHJ7D6aDHQ+SxtzSL6HY0s9O4EWBx4QLWz7XyqSlB1sSFmxSBI8ijHovkc0prqKLcHmKwyR4dOrociZBRHin0QPkoTl3jqkCc=
